// Writes src/environments/environment.ts from environment variables.
//
// Only PUBLIC values go in this file: it is compiled into the browser bundle.
// Sources, in order of precedence: real environment variables (Vercel), then .env.local, then .env.
//
// Usage:
//   node scripts/write-env.mjs               always (re)write
//   node scripts/write-env.mjs --if-missing  write only when the file does not exist yet

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const target = join(root, 'src', 'environments', 'environment.ts');

if (process.argv.includes('--if-missing') && existsSync(target)) {
  process.exit(0);
}

// process.loadEnvFile never overrides variables that are already set.
for (const file of ['.env.local', '.env']) {
  const path = join(root, file);
  if (existsSync(path)) {
    process.loadEnvFile(path);
  }
}

const supabaseUrl = (process.env.SUPABASE_URL ?? '').trim();
const supabasePublishableKey = (process.env.SUPABASE_PUBLISHABLE_KEY ?? '').trim();

if (supabasePublishableKey.startsWith('sb_secret_')) {
  console.error(
    '[write-env] SUPABASE_PUBLISHABLE_KEY holds a secret key. Refusing to write it into the browser bundle.',
  );
  process.exit(1);
}

const contents = `// Generated by scripts/write-env.mjs. Do not edit and do not commit.
// Only public values belong here: this file is compiled into the browser bundle.
export const environment = {
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabasePublishableKey: ${JSON.stringify(supabasePublishableKey)},
} as const;
`;

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, contents, 'utf8');

if (!supabaseUrl || !supabasePublishableKey) {
  console.warn(
    '[write-env] SUPABASE_URL or SUPABASE_PUBLISHABLE_KEY is not set. The app will start in "not configured" mode. See .env.example.',
  );
} else {
  console.log('[write-env] wrote src/environments/environment.ts');
}
